name: HelpfulHelp
description: Interactive help menu.

author: SavageAvocado
website: https://www.savagedev.net/

main: net.savagedev.helpfulhelp.HelpfulHelp
version: ${version}

commands:
  helpreload:
    description: Reload the HelpfulHelp plugin.
    permission: help.reload
    aliases: [ helprl ]
  help:
    description: Displays a help message.
    aliases: [ "?" ]

permissions:
  help.reload:
    default: op
